# Generated by Django 5.2.13 on 2026-04-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='allowed_domains',
        ),
        migrations.RemoveField(
            model_name='license',
            name='company_id',
        ),
        migrations.AddField(
            model_name='license',
            name='domain',
            field=models.CharField(db_index=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
