# Generated by Django 5.2.13 on 2026-04-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_remove_license_allowed_domains_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='domain',
            new_name='tenant',
        ),
    ]
